In [1]:
import torch
data = [
    [1, 1.5, 1, 1, 1, 0.8],
    [1.2, 1.8, 0.9, 0.8, 0.9, 0.64],
    [1.44, 2.16, 1.1, 1.2, 1.1, 0.96],
    [1.5, 2.25, 1, 1.4, 1, 1.12],
    [1, 1, 1.1, 1, 0.95, 0.7],
    [1.6, 0.85, 1.76, 0.8, 0.8075, 0.56],
    [1.4, 1.05, 1.54, 1, 0.9975, 0.7],
    [1.2, 1, 1.32, 1.2, 0.95, 0.84],
    [1, 1, 1, 1, 1, 1],
    [0.7, 0.7, 0.8, 0.8, 1.1, 1.1],
    [0.8, 0.8, 0.9, 0.9, 1.2, 1.2],
    [0.9, 0.9, 1, 1, 1.3, 1.3]
]
tensor = torch.tensor(data)
print(tensor)

tensor([[1.0000, 1.5000, 1.0000, 1.0000, 1.0000, 0.8000],
        [1.2000, 1.8000, 0.9000, 0.8000, 0.9000, 0.6400],
        [1.4400, 2.1600, 1.1000, 1.2000, 1.1000, 0.9600],
        [1.5000, 2.2500, 1.0000, 1.4000, 1.0000, 1.1200],
        [1.0000, 1.0000, 1.1000, 1.0000, 0.9500, 0.7000],
        [1.6000, 0.8500, 1.7600, 0.8000, 0.8075, 0.5600],
        [1.4000, 1.0500, 1.5400, 1.0000, 0.9975, 0.7000],
        [1.2000, 1.0000, 1.3200, 1.2000, 0.9500, 0.8400],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.7000, 0.7000, 0.8000, 0.8000, 1.1000, 1.1000],
        [0.8000, 0.8000, 0.9000, 0.9000, 1.2000, 1.2000],
        [0.9000, 0.9000, 1.0000, 1.0000, 1.3000, 1.3000]])


In [12]:
A=  torch.tensor( [[
    [1, 1, 1],
    [1.2, 0.9, 0.8],
    [1.44,  1.1, 1.2],
    [1.5, 1, 1.4],
],[[1, 1, 1],
    [1.6, 0.85, 0.8],
    [1.4, 1.05,  1],
    [1.2, 1,  1.2]],[[1,  1, 1],
    [0.7, 0.8,  1.1],
    [0.8,  0.9, 1.2],
    [0.9,  1,  1.3]]])

B=  torch.tensor( [[[1,1.5,0,0,0,0],[0,0,1,0,1,0],[0,0,0,1,0,0.8]],[[1,0,1.1,0,0,0],[0,1,0,0,0.95,0],[0,0,0,1,0,0.7]],[[1,1,0,0,0,0],[0,0,1,1,0,0],[0,0,0,0,1,1]]])

data = torch.tensor( [[
    [1, 1.5, 1, 1, 1, 0.8],
    [1.2, 1.8, 0.9, 0.8, 0.9, 0.64],
    [1.44, 2.16, 1.1, 1.2, 1.1, 0.96],
    [1.5, 2.25, 1, 1.4, 1, 1.12]],
    [[1, 1, 1.1, 1, 0.95, 0.7],
    [1.6, 0.85, 1.76, 0.8, 0.8075, 0.56],
    [1.4, 1.05, 1.54, 1, 0.9975, 0.7],
    [1.2, 1, 1.32, 1.2, 0.95, 0.84]],[
    [1, 1, 1, 1, 1, 1],
    [0.7, 0.7, 0.8, 0.8, 1.1, 1.1],
    [0.8, 0.8, 0.9, 0.9, 1.2, 1.2],
    [0.9, 0.9, 1, 1, 1.3, 1.3]]])
C=A@B
print(data)
print(C)
if torch.allclose(A@B, data):
    print("The tensors are equal.")
else:
    print("The tensors are not equal.")


tensor([[[1.0000, 1.5000, 1.0000, 1.0000, 1.0000, 0.8000],
         [1.2000, 1.8000, 0.9000, 0.8000, 0.9000, 0.6400],
         [1.4400, 2.1600, 1.1000, 1.2000, 1.1000, 0.9600],
         [1.5000, 2.2500, 1.0000, 1.4000, 1.0000, 1.1200]],

        [[1.0000, 1.0000, 1.1000, 1.0000, 0.9500, 0.7000],
         [1.6000, 0.8500, 1.7600, 0.8000, 0.8075, 0.5600],
         [1.4000, 1.0500, 1.5400, 1.0000, 0.9975, 0.7000],
         [1.2000, 1.0000, 1.3200, 1.2000, 0.9500, 0.8400]],

        [[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [0.7000, 0.7000, 0.8000, 0.8000, 1.1000, 1.1000],
         [0.8000, 0.8000, 0.9000, 0.9000, 1.2000, 1.2000],
         [0.9000, 0.9000, 1.0000, 1.0000, 1.3000, 1.3000]]])
tensor([[[1.0000, 1.5000, 1.0000, 1.0000, 1.0000, 0.8000],
         [1.2000, 1.8000, 0.9000, 0.8000, 0.9000, 0.6400],
         [1.4400, 2.1600, 1.1000, 1.2000, 1.1000, 0.9600],
         [1.5000, 2.2500, 1.0000, 1.4000, 1.0000, 1.1200]],

        [[1.0000, 1.0000, 1.1000, 1.0000, 0.9500

In [ ]:
A=  torch.tensor( [
    [1, 1, 1],
    [1.2, 0.9, 0.8],
    [1.44,  1.1, 1.2],
    [1.5, 1, 1.4],
])

B=  torch.tensor( [[1,1.5,0,0,0,0],[0,0,1,0,1,0],[0,0,0,1,0,0.8]])

data = torch.tensor( [
    [1, 1.5, 1, 1, 1, 0.8],
    [1.2, 1.8, 0.9, 0.8, 0.9, 0.64],
    [1.44, 2.16, 1.1, 1.2, 1.1, 0.96],
    [1.5, 2.25, 1, 1.4, 1, 1.12]])

if torch.allclose(A@B, data):
    print("The tensors are equal.")
else:
    print("The tensors are not equal.")